import type { Metadata } from "next";
import { Inter as FontSans, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import TopNavigation from "./components/TopNavigation";
import Footer from "./components/Footer";
import BaseNavbar from "./components/BaseNavbar";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
        suppressHydrationWarning={true}
      >
        <TopNavigation />

        <BaseNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
